name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: ./src
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: build prod
        run: npm run build:prod

      - name: run lint:ts
        run: npm run lint:ts
        if: always()

      - name: run lint:scss
        run: npm run lint:scss
        if: always()

      - name: run test:unit
        run: npm run test:unit
        if: always()

      - name: run test:unit
        run: npm run test:unit
        if: always()

      - name: run storybook:build
        run: npm run storybook:build
        if: always()

      - name: run screenshot testing
        run: npm run test:ui:ci
        if: always()
